### ISSUE TITLE
clean up

### ISSUE THREAD

**Issue by TillSchlemmermeier** [TillSchlemmermeier/l3d-controller-software#6]
lets put all the G's and E's in folders to clean up the filestructure and get rid of deprecated files

**Comment by Co-eus** [comment]
- [ ] check cube_utils for old routines
- [ ] delete gui_1.2.py
- [ ] put gui stuff in a seperate routine/file, so that the main file is cleaner
- [ ] automatic addition of generators/effects using os.listdir or os.path
